### ISSUE TITLE
Looking for a new maintainer for vulnix

### ISSUE THREAD

**Issue by ckauhaus** [nix-community/vulnix#87]
Hi everyone,

currently I do not have enough time to maintain vulnix. So I would be glad if someone could step in and take care of vulnix' further development. I do have a few ideas/suggestions what would be sensible next steps so I would be willing to share my thoughts with anyone who is interested.

I'm thankful for everyone who contributed ideas, bug reports and patches. Apologies for not taking care of them lastly.

--- 

https://discourse.nixos.org/t/vulnix-new-maintainer-needed/27209

**Comment by MostAwesomeDude** [comment]
What needs to be done? I can't promise my time yet; it really depends on what you wanted to achieve and what needs to be maintained over time.

**Comment by adisbladis** [comment]
The project has been moved to nix-community with should help with co-maintainership & co-governance.

Someone still needs to step up as maintainer, though this should be easier within the nix-community org.

**Comment by ckauhaus** [comment]
Continue discussion here: https://github.com/nix-community/vulnix/

**Comment by MikaelFangel** [comment]
@adisbladis Still needing a maintainer?

**Comment by stnert** [comment]
@ckauhaus And then? Did you find maintainers?
